- name: update and upgrade system
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400


- name: Print a message
  ansible.builtin.debug:
    msg: "this task runs after the example role"


- name: Install web server
  apt:
    name: "apache2"
    state: present

- name: python pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: create a directory
  ansible.builtin.file:
    path: $HOME/todo_project
    state: directory


- name: Install MyApp using one of the remote protocols (bzr+,hg+,git+)
  ansible.builtin.copy:
    url: https://github.com/lowryel/todoapp.git
    dest: $HOME/todo_project


# - name: copy app folder to remote
#   ansible.builtin.copy:
#     src: "/root/project/{{ item }}"
#     remote_src: yes
#     dest: $HOME/todo_project
#     follow: yes
#   loop:
#     - taskapp
#     - static
#     - templates
#     - to_do
#     - db.sqlite3
#     - manage.py
#     - requirements.txt

- name: install python dependencies
  ansible.builtin.pip:
    requirements: $HOME/todo_project/requirements.txt





